services:
  - type: web
    name: biasshield-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_API_KEY
        value: "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"
      - key: MONGO_URI
        value: "mongodb+srv://rolexcoderpro:JTUVIwRVYmkKvhyp@cluster0.myj0eqp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    autoDeploy: true
